services:
  postgres:
    image: 'postgres'
    environment:
      - 'POSTGRES_DB=eco_postgres_PONOinput'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5441:5432'
