spring.application.name=eco_service_PONOinput


# Server configuration
server.port=8083

# Database configuration
# DBeaver: Host=localhost, Port=5441, Database=eco_postgres_PONOinput (именно это имя, не postgres!)
spring.datasource.url=jdbc:postgresql://localhost:5441/eco_postgres_PONOinput
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none


springdoc.show-actuator=true


springdoc.default-produces-media-type=application/json